
// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// CUSTOMERADDRESS
export const CREATE_CUSTOMERADDRESS_SUCCESS = "CREATE_CUSTOMERADDRESS_SUCCESS";
export const DELETE_CUSTOMERADDRESS_SUCCESS = "DELETE_CUSTOMERADDRESS_SUCCESS";
export const FINDBYADDRESSTYPEID_CUSTOMERADDRESS_SUCCESS = "FINDBYADDRESSTYPEID_CUSTOMERADDRESS_SUCCESS";
export const GET_CUSTOMERADDRESS_SUCCESS = "GET_CUSTOMERADDRESS_SUCCESS";
export const LIST_CUSTOMERADDRESS_SUCCESS = "LIST_CUSTOMERADDRESS_SUCCESS";
export const UPDATE_CUSTOMERADDRESS_SUCCESS = "UPDATE_CUSTOMERADDRESS_SUCCESS";

// CUSTOMERGROUP
export const LIST_CUSTOMERGROUP_SUCCESS = "LIST_CUSTOMERGROUP_SUCCESS";

// CUSTOMERS
export const CREATE_CUSTOMERS_SUCCESS = "CREATE_CUSTOMERS_SUCCESS";
export const DELETE_CUSTOMERS_SUCCESS = "DELETE_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const LIST_CUSTOMERS_SUCCESS = "LIST_CUSTOMERS_SUCCESS";
export const UPDATE_CUSTOMERS_SUCCESS = "UPDATE_CUSTOMERS_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// LU_ADDRESSTYPE
export const CREATE_LU_ADDRESSTYPE_SUCCESS = "CREATE_LU_ADDRESSTYPE_SUCCESS";
export const DELETE_LU_ADDRESSTYPE_SUCCESS = "DELETE_LU_ADDRESSTYPE_SUCCESS";
export const GET_LU_ADDRESSTYPE_SUCCESS = "GET_LU_ADDRESSTYPE_SUCCESS";
export const LIST_LU_ADDRESSTYPE_SUCCESS = "LIST_LU_ADDRESSTYPE_SUCCESS";
export const UPDATE_LU_ADDRESSTYPE_SUCCESS = "UPDATE_LU_ADDRESSTYPE_SUCCESS";

// LU_EMPLOYEES
export const CREATE_LU_EMPLOYEES_SUCCESS = "CREATE_LU_EMPLOYEES_SUCCESS";
export const DELETE_LU_EMPLOYEES_SUCCESS = "DELETE_LU_EMPLOYEES_SUCCESS";
export const GET_LU_EMPLOYEES_SUCCESS = "GET_LU_EMPLOYEES_SUCCESS";
export const LIST_LU_EMPLOYEES_SUCCESS = "LIST_LU_EMPLOYEES_SUCCESS";
export const UPDATE_LU_EMPLOYEES_SUCCESS = "UPDATE_LU_EMPLOYEES_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
